parameters:
- name: environment
  type: string
  default: 'dev'
  values:
    - dev
    - qa
    - prod

stages:
- stage: 'ecosystem_integration'
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
    displayName: 'Ecosystem Integration Development'
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/release') }}:
    displayName: 'Ecosystem Integration Release'
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/support') }}:
    displayName: 'Ecosystem Integration Production Atp'
  ${{ if or(in(variables['Build.SourceBranch'], 'refs/heads/master' , 'refs/heads/main'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')) }}:
    displayName: 'Ecosystem Integration Production'

  dependsOn:
    - 'artifacts_managment'

  jobs:
    # 1) IaC con Terraform
    - job: iac_${{ parameters.environment }}
      displayName: 'IaC Terraform (${{ parameters.environment }})'
      steps:
        - template: terraform-iac.yml
          parameters:
            environment: ${{ parameters.environment }}

    # 2) Despliegue a Kubernetes (usa el artefacto ya generado en stages previos)
    - job: k8s_deploy_${{ parameters.environment }}
      displayName: 'Kubernetes deploy (${{ parameters.environment }})'
      dependsOn: iac_${{ parameters.environment }}
      steps:
        - template: jobs/kubernetes-deploy-jobs.yml
          parameters:
            environment: ${{ parameters.environment }}

    # 3) Actualización GitOps (values-<env>.yaml)
    - job: gitops_update_${{ parameters.environment }}
      displayName: 'GitOps update values-${{ parameters.environment }}.yaml'
      dependsOn: k8s_deploy_${{ parameters.environment }}
      steps:
        - template: jobs/Update-tag.yml
          parameters:
            environment: ${{ parameters.environment }}
            imageTag: $(Build.BuildNumber)   # o el tag que definas en 3.1
